module.exports = {
  APPOINTMENT: {
    CONFIRMED: 'CONFIRMED',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    NO_SHOW: 'NO_SHOW',
  },
  SLOT: {
    AVAILABLE: 'AVAILABLE',
    BOOKED: 'BOOKED',
    BLOCKED: 'BLOCKED',
  },
  THERAPY_SESSION: {
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED',
    SKIPPED: 'SKIPPED',
  },
  CHAT_STATUS: {
    OPEN: 'OPEN',
    ESCALATED_TO_DOCTOR: 'ESCALATED_TO_DOCTOR',
    CLOSED: 'CLOSED',
  },
};
